// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title ZKVerifier
 * @dev Base contract for zero-knowledge proof verification
 * This contract will be extended by specific verifier contracts generated by Circom/SnarkJS
 */
abstract contract ZKVerifier {
    /**
     * @dev Verify a zero-knowledge proof
     * @param a First proof component
     * @param b Second proof component
     * @param c Third proof component
     * @param input Public inputs to the proof
     * @return bool True if the proof is valid
     */
    function verifyProof(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[] memory input
    ) public view virtual returns (bool);
}

/**
 * @title ZKAccessControl
 * @dev Access control using zero-knowledge proofs
 */
contract ZKAccessControl {
    struct AccessPolicy {
        string policyId;
        string resourceId;
        string requiredCredentialType;
        uint256 minAge;
        bool requireMembership;
        address verifierContract;
        bool active;
    }

    struct AccessRequest {
        address requester;
        string resourceId;
        uint256 timestamp;
        bool granted;
    }

    // policyId => AccessPolicy
    mapping(string => AccessPolicy) public policies;
    
    // resourceId => policyId
    mapping(string => string) public resourcePolicies;
    
    // requester => AccessRequest[]
    mapping(address => AccessRequest[]) public accessHistory;
    
    // Granted access: requester => resourceId => expiration
    mapping(address => mapping(string => uint256)) public grantedAccess;

    address public admin;
    uint256 public defaultAccessDuration = 24 hours;

    event PolicyCreated(string indexed policyId, string indexed resourceId);
    event PolicyUpdated(string indexed policyId);
    event AccessGranted(address indexed requester, string indexed resourceId, uint256 expiration);
    event AccessRevoked(address indexed requester, string indexed resourceId);
    event ProofVerified(address indexed requester, string indexed resourceId, bool success);

    modifier onlyAdmin() {
        require(msg.sender == admin, "Only admin can perform this action");
        _;
    }

    constructor() {
        admin = msg.sender;
    }

    /**
     * @dev Create a new access policy
     */
    function createPolicy(
        string memory policyId,
        string memory resourceId,
        string memory requiredCredentialType,
        uint256 minAge,
        bool requireMembership,
        address verifierContract
    ) external onlyAdmin {
        require(bytes(policies[policyId].policyId).length == 0, "Policy already exists");
        require(verifierContract != address(0), "Invalid verifier contract");

        policies[policyId] = AccessPolicy({
            policyId: policyId,
            resourceId: resourceId,
            requiredCredentialType: requiredCredentialType,
            minAge: minAge,
            requireMembership: requireMembership,
            verifierContract: verifierContract,
            active: true
        });

        resourcePolicies[resourceId] = policyId;

        emit PolicyCreated(policyId, resourceId);
    }

    /**
     * @dev Request access with zero-knowledge proof
     */
    function requestAccess(
        string memory resourceId,
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[] memory publicInputs
    ) external returns (bool) {
        string memory policyId = resourcePolicies[resourceId];
        require(bytes(policyId).length > 0, "No policy for this resource");
        
        AccessPolicy memory policy = policies[policyId];
        require(policy.active, "Policy is not active");

        // Verify the zero-knowledge proof
        ZKVerifier verifier = ZKVerifier(policy.verifierContract);
        bool proofValid = verifier.verifyProof(a, b, c, publicInputs);

        emit ProofVerified(msg.sender, resourceId, proofValid);

        if (proofValid) {
            uint256 expiration = block.timestamp + defaultAccessDuration;
            grantedAccess[msg.sender][resourceId] = expiration;

            accessHistory[msg.sender].push(AccessRequest({
                requester: msg.sender,
                resourceId: resourceId,
                timestamp: block.timestamp,
                granted: true
            }));

            emit AccessGranted(msg.sender, resourceId, expiration);
            return true;
        } else {
            accessHistory[msg.sender].push(AccessRequest({
                requester: msg.sender,
                resourceId: resourceId,
                timestamp: block.timestamp,
                granted: false
            }));
            return false;
        }
    }

    /**
     * @dev Check if address has valid access to resource
     */
    function hasAccess(address requester, string memory resourceId) external view returns (bool) {
        uint256 expiration = grantedAccess[requester][resourceId];
        return expiration > block.timestamp;
    }

    /**
     * @dev Revoke access for an address
     */
    function revokeAccess(address requester, string memory resourceId) external onlyAdmin {
        delete grantedAccess[requester][resourceId];
        emit AccessRevoked(requester, resourceId);
    }

    /**
     * @dev Update access duration
     */
    function setAccessDuration(uint256 duration) external onlyAdmin {
        defaultAccessDuration = duration;
    }

    /**
     * @dev Deactivate a policy
     */
    function deactivatePolicy(string memory policyId) external onlyAdmin {
        require(policies[policyId].active, "Policy is already inactive");
        policies[policyId].active = false;
        emit PolicyUpdated(policyId);
    }

    /**
     * @dev Get access history for a requester
     */
    function getAccessHistory(address requester) external view returns (AccessRequest[] memory) {
        return accessHistory[requester];
    }

    /**
     * @dev Update verifier contract for a policy
     */
    function updateVerifier(string memory policyId, address newVerifier) external onlyAdmin {
        require(policies[policyId].active, "Policy does not exist");
        require(newVerifier != address(0), "Invalid verifier address");
        
        policies[policyId].verifierContract = newVerifier;
        emit PolicyUpdated(policyId);
    }

    /**
     * @dev Transfer admin role
     */
    function transferAdmin(address newAdmin) external onlyAdmin {
        require(newAdmin != address(0), "Invalid admin address");
        admin = newAdmin;
    }
}
